### ISSUE TITLE
can you clarify the instructions?

### ISSUE THREAD

**Issue by ktrinanm** [varunsridharan/pi-hole-android-private-dns#3]
**Describe the bug**
* I'm not sure what "Allow The Following Ports in TCP" means. is that opening those ports in the firewall on the host that has pi.hole installed?
* do we need an existing domain name registered?
* what do we then put in the android private dns hostname field?

**To Reproduce**
Reading README

**Desktop (please complete the following information):**
 - Raspbian on raspberry pi

**Smartphone (please complete the following information):**
 - Device: Google PIxel
 - OS: Android Q (Android 10)
 - Browser Chrome
 - Version not sure

**Additional context**

**Comment by varunsridharan** [comment]
1. I'm not sure what "Allow The Following Ports in TCP" means. is that opening those ports in the firewall on the host that has pi.hole installed?

_Yes Exactly you need to open those ports `80,443` is required to SSL Certificate and `853` to run the DNS Stream for android phones.  you can remove port `80 & 443` once you have installed and this. but you need to open this port every 90days to get the certificate renewed_

---

2. do we need an existing domain name registered ?

_Yes you need a domain name. for example me i would use like this `pi.svarun.dev`_

---

3. what do we then put in the android private dns hostname field

_Domain name of your choice . example you can use apex domain `your-name-pihole.com` or subdomain `pihole-yourname.com`_
