### ISSUE TITLE
Script uses unavailable packages.

### ISSUE THREAD

**Issue by R3velation** [varunsridharan/pi-hole-android-private-dns#4]
The shell script will try to install `python-software-properties` and `python-certbot-nginx` and will fail as neither of these packages are in the mainline repository.

python-software-properties was merged into `software-properties-common`, and python-certbot-nginx is now `python3-certbot-nginx`

This is on Ubuntu LTS 20.04.1

**Comment by varunsridharan** [comment]
@R3velation thanks for informing about this. i will look & update it when i get some free time.

**Comment by varunsridharan** [comment]
@Danderlion i just updated this repository with the automated script for PiHole5 
https://github.com/varunsridharan/pi-hole-android-private-dns/blob/main/pi-hole5.sh

**Comment by varunsridharan** [comment]
@Danderlion 

> I have another issue. It causes a permanent 301 redirection loop. Any idea where that might come from?

I am not sure what's causing this issue. i have no idea.! may be if you could replicate the same in a server and provide details to it i can try to debug and figure out the issue.

**Comment by eisengrau** [comment]
The source of the errors may come from the step when nginx is installed: port 80 is already bound to pihole's lighthttpd, aka web interface. Would be wise to disable the default port 80 host at nginx install... or find a different solution cirumventing this.
