### ISSUE TITLE
not working for pihole with docker 

### ISSUE THREAD

**Issue by sreejithag** [varunsridharan/pi-hole-android-private-dns#5]
Hi,
I tried to run the script inside of the official pihole docker image 
but i was not able to run the nginx inside the container 
was getting error

"s6 service not found for nginx, exiting..."
for sudo service nginx restart
any idea what is the cause of it 
or any way to implement it along the docker container

**Comment by sreejithag** [comment]
No issues i got it working without using docker

**Comment by ang3lo-azevedo** [comment]
> No issues i got it working without using docker

Did you move your whole pi-hole to outside of a docker container?
