### ISSUE TITLE
I've done this but I get error on phone

### ISSUE THREAD

**Issue by vanjavk** [varunsridharan/pi-hole-android-private-dns#6]
**Describe the bug**

**To Reproduce**
1. Go to install following instruction
2. Click on random page
3. Scroll down to see error message ERR_NAME_NOT_RESOLVED

**Expected behavior**
page loads without ads

**Screenshots**
just basic chrome

**Smartphone (please complete the following information):**
android 10 miui

**Additional context**
server is hosted on ubuntu linux with pihole and self updating dynamic dns domain

**Comment by varunsridharan** [comment]
Hi There

Sorry i can't able to replicate the issue. do you mind providing more info ? like that it shows in android phone's private dns configuration page ?

**Comment by vanjavk** [comment]
I've decided to use public servers and they seem to work fine
